OTT
cesbo/www pull request #12
Opened 2022-11-04 12:56 UTC by Csarag

Есть вариант дополнить вариантами монетизации и еще долить воды по поводу функционала

2022-11-05 21:10 UTC, and-cesbo requested changes

2022-11-05 21:10 UTC, and-cesbo commented on en/alta/ott/info.md
> +### VOD abd LIVE
тут опечатка, "and" но лучше разделить на два раздела.
Live - там не только спорт, но и любое потоковое ТВ, потоки с камер наблюдения (хотя это уже не совсем ОТТ и может быть тут лишним)

2022-11-05 21:10 UTC, and-cesbo commented on en/alta/ott/info.md
> +### OTT technology  in action:
В нашем случае получается так:

1. "Service provider" (может это лучше использовать вместо "Broadcasters") устанавливает у себя необходимое программное обеспечение. тонкий намёк на наше ПО :)
2. В ПО добавляет медиа-потоки из различных источников (ТВ, Камеры, Видео-архив)
3. ПО формирует сегменты и распределяет их по CDN
4. Пользователь выбирает контенте...
5. Видео плеер получается медиа контент из CDN с наиболее оптимального узла (менее загруженный или расположен ближе к пользователю)

2022-11-05 21:15 UTC, and-cesbo commented
Монетизации это не обязательно. Тут много разных вариантов, каждый сам решает. У некоторых это просто бесплатное дополнение к другим услугам.

2022-11-05 21:20 UTC, and-cesbo commented
можно написать про транскодирование. (в ABR)
что это технология формирования из видео выокого качества несколько разных
ещё погуглил немного. есть термин мультибитрейт... насколько я понял получается на входе видео высокого качества. Потом идёт транскодирование. Получается видео с мультибитрейтом. Далее уже плеер пытается получить контент наилучшего качества - это адаптивный битрейт.

2022-11-05 21:22 UTC, Csarag commented
Понял, сегодня все будет

2022-11-05 21:31 UTC, and-cesbo commented
выходной же. работать вредно :)

2022-11-06 10:19 UTC, Csarag commented
Приври внесены

2022-11-07 11:06 UTC, Csarag commented
Все правки внесены, разве что возникает ошибка при переходе по ссылке

2022-11-07 11:17 UTC, and-cesbo commented
> Все правки внесены, разве что возникает ошибка при переходе по ссылке

там скобок много. надо `[Read more](/en/book/protocols/hls/){target="_blank"}` оно потом когда соберётся в доку нормально будет.
вот тут пример как такая сноска работает : https://cesbo.com/en/alta/ott/channels/config/#hls-media-playlist

2022-11-07 11:30 UTC, Csarag commented
<img width="462" alt="Снимок экрана 2022-11-07 в 12 29 07" src="https://user-images.githubusercontent.com/86711086/200299690-1e4e3572-122a-43eb-8464-c53e91b98b9b.png">

Сделал, но все вот так теперь. Ошибка не исчезла

2022-11-07 11:55 UTC, and-cesbo commented
Всё ок если собирать через `make en-alta` (оно запускает `mkdocs build -c -f en-alta.yml` )
Там ещё в тексте, в разделе ABR перед сноской `HLS[^1]` есть &#96;

2022-11-07 11:57 UTC, Csarag commented
Пофиксил - готово

2022-11-07 13:10 UTC, and-cesbo approved these changes

2022-11-07 13:10 UTC, merged