UDP + IPTV
cesbo/www pull request #13
Opened 2022-11-10 11:52 UTC by Csarag

Много чего порезал и выкинул в целях укорачивания. Из штук, которые можно добавить при необходимости:
Различия TCP/UDP
Более подробное описание работы каждого из пунктов (Мультикаст, UDP и т.п.)
ICMP
PIM

2022-11-11 11:01 UTC, Csarag commented
ну так как?

2022-11-11 11:23 UTC, and-cesbo requested changes

2022-11-11 11:23 UTC, and-cesbo commented on en/book/protocols/udp.md
> +> The centralised architecture model is a relatively simple and easy to manage solution. Because all media content is stored in centralised servers, it does not require a comprehensive content distri
Тут в начале говорится, что не требуется (CDN) , это правильно. А последнее предложение говорит про CDN. Тут лучше сказать, что централизованная архитектура требует:
- сеть с большой пропускной способностью и минимальными задержками
- резервирование ядра сети для бесперебойной доставки контента
- ну и вот распределённая архитектура если сеть большая.

Для примера (просто рассказать) есть клиент у нас, его сеть на несколько городов.
Два основных узла в сети "север" и "юг" (несколько городов рядом с одним ядром, и несколько рядом с другим).
Между основными узлами 300км примерно.
Каждый основной узел сам принимает все необходимые каналы.
Городские узлы принимают каналы со своего основного узла. Если свой узел становится недоступным, то каналы начинаю приниматься со второго узла.
Клиенты каналы принимаю уже с городского узла, они даже не заметят если что-то не так будет с одним из узлов.

В этом примере получается:
- между городами должна быть очень хорошая сеть, прямое соединение от каждого города на оба основных узла
- два основных узла для резерва - это уже распределённая архитектура

2022-11-11 11:26 UTC, and-cesbo commented
напиши ещё пожалуйста после Multicast раздел (без картинок, это не особо важно):

- Broadcast - первой фразой - "никогда не используйте это!", ну и дальше кратко, что это раздача контента от одного источника на всю локальную сеть
- Unicast - передача данных от одной точки к другой - единственный способ передать данные через Internet, как правило Unicast используется в протоколах более высокого уровня, например RTSP, SRT

2022-11-11 11:29 UTC, Csarag commented
Понял, сегодня будет

2022-11-11 11:36 UTC, and-cesbo commented
Если что какие вопросы будут, пиши мне в телеграмме : https://t.me/and_cesbo
Могу подробней расказать как оно всё у нас устроено.

2022-11-13 10:22 UTC, and-cesbo requested changes

2022-11-13 10:22 UTC, and-cesbo commented on en/book/protocols/udp.md
> +### How Does UDP Work?
Давай тут заголовок второго уровня `##`

2022-11-13 10:22 UTC, and-cesbo commented on en/book/protocols/udp.md
> +Group communication may either be application layer multicast or network-assisted multicast, where the latter makes it possible for the source to efficiently send to the group in a single transmissio
Надо брать " or InfiniBand multicast. Network-assisted multicast may also be implemented at the Internet layer using IP multicast"
InfiniBand - с 2019 года больше не существует (используется, но сама технология уже всё).
мультикаст в интернете - тут могу ошибаться, но я не знаю примеров чтобы оно использовалось, там много ограничений на такие свободно летающие пакеты, только точка-точка в интернете допускается.

2022-11-13 10:22 UTC, and-cesbo commented on en/book/protocols/udp.md
> +In computer networking, unicast is a one-to-one transmission from one point in the network to another point; that is, one sender and one receiver, each identified by a network address.
Дополни пожалуйста, что unicast как правило используется в протоколах более высокого уровня - RTSP, SRT

2022-11-13 10:22 UTC, and-cesbo commented on en/book/protocols/udp.md
> +Detailed description available in the [RFC 768][RFC 768] standard.
Сноску надо : `RFC768[^1]`
И внизу: `[^1]: RFC 768 [Read more](https://www.rfc-editor.org/rfc/rfc768){target="_blank"}`

2022-11-13 10:22 UTC, and-cesbo commented on en/book/protocols/udp.md
> +- HTTP MPEG-TS - constant distribution of one file (streaming). A little bit more delay with a better stability.
про HTTP MPEG-TS - давай просто последнее предложение. что чуть больше задержка. а как оно работает это отдельно напишем

2022-11-13 10:22 UTC, and-cesbo commented on en/book/protocols/udp.md
> +## Protocols main features
давай заголовок `Protocols comparison`

2022-11-13 10:22 UTC, and-cesbo commented on en/book/protocols/udp.md
> +- HLS - long delay but it has best data transfer stability and adaptive bitrate.
Сделай пожалуйста ссылку `HLS[^2]`
И в самом низу: `[^2]: HLS - HTTP Live Streaming protocol. [Read more](/en/book/protocols/hls/){target="_blank"}`

2022-11-14 12:26 UTC, and-cesbo approved these changes

2022-11-14 12:26 UTC, merged